name: Aggiornamento Automatico Dati FCI

on:
  schedule:
    - cron: '40 22 * * *' # Gira ogni giorno alle 18:00 UTC
  workflow_dispatch: # Permette di avviarlo a mano con un tasto

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Esegui lo script
        run: python estrattore.py

      - name: Salva e Pusha il CSV nel repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add risultati_juniores.csv
          # Il commit viene creato solo se ci sono modifiche effettive
          git commit -m "Update dati: $(date)" || exit 0
          # Il pull --rebase risolve il problema del 'rejected' scaricando prima i tuoi file aggiornati
          git pull --rebase origin main
          git pushultati_juniores.csv
          git commit -m "Update dati: $(date)" || exit 0
          git push
